In [33]:
import pandas as pd
import numpy as np

# Introduccion en el paquete Numpy, No hay que instalar nada, ya esta dentro de Anaconda.
# Numpy es que paquete orientado a analisis matematico y cientifico de datos.

#Traemos las DF
data = pd.read_csv("data.csv.csv")
data.head(10)

# Matiz. 
# Dos Dimenciones
valoraciones = np.array([[8,7,8,5], [2,6,8,1], [8,8,9,5]])
valoraciones

#ouput:
#array([[8, 7, 8, 5],
#      [2, 6, 8, 1],
#      [8, 8, 9, 5]])

# Como acceder a los datos de las "valoraciones"
# hay dos formas.
valoraciones[0][1] # Opcion 1
valoraciones[0,1] # Opcion 2

# Tres Dimenciones.
valoraciones2 = np.array([[[8,7,8,5], [2,6,8,1]], [[8,8,9,5], [2,6,8,4]], [[8,9,7,4], [8,8,9,3]]])
valoraciones2

# ouput:
# array 
# array([[[8, 7, 8, 5],
#       [2, 6, 8, 1]],
#
#      [[8, 8, 9, 5],
#       [2, 6, 8, 4]],
#
#      [[8, 9, 7, 4],
#       [8, 8, 9, 3]]])

# como aceder a los valores de las "valoraciones"
valoraciones2[0][1][2]
valoraciones2[0,1,3]

# Generar dimenciones en cero
np.zeros((2,3,5))

# Suma de dimenciones de iguales dimencion, Le sumamos uno con ones
valoraciones2 + np.ones((3,2,4))

# Calcular la media 
np.mean(valoraciones)

# Crear una dimencion a partir de un array.
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12], (3,2,2)) # tener en cuenta que la cantidad de valores coincidan, Sino da error.





array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])